name: Build Client

on: [push]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker run --rm -v .\service:c:\app  mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809 "c:\app\scripts\build.bat"
