name: Build Client

on: 
  push:
    paths:
    - client/**
    - .github/workflows/build-client.yml

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build the application
      run: Invoke-Expression "docker run --rm -v $(pwd)\client:c:\app  mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1809 `"c:\app\scripts\build.bat`""
    
    - name: Check results
      run: if (Test-Path ".\client\build\client.dll" -PathType Leaf) { Write-Host "Built application successfully" } else { Write-Error "Application failed to build" }

